{
 "title": "All at once",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Files count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mongodb_files_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chunks count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "mongodb_chunks_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Candidates count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "mongodb_candidates_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clone counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "mongodb_clones_count", "legendFormat": "__auto" }
   ]
  }
 ]
}